name: 'Deploy a Deploy Request'
description: 'Deploys an open deploy request for a PlanetScale database.'
branding:
  color: 'orange'
  icon: 'database'
inputs:
  database_name:
    description: 'The name of the database.'
    required: true
  number:
    description: 'The number of the deploy request to deploy. Defaults to the latest deploy request.'
    required: false
  org_name:
    description: 'The name of the organization that owns the database.'
    required: true
  wait:
    description: 'If set to `true`, this action will wait for the deploy request to merge before exiting.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.database_name }}
    - ${{ inputs.number }}
    - ${{ inputs.org_name }}
    - ${{ inputs.wait }}